export const znrList = [
  { index: 0, name: "Acquisitions Expert" },
  { index: 1, name: "Akoum Warrior // Akoum Teeth" },
  { index: 2, name: "Allied Assault" },
  { index: 3, name: "Attended Healer" },
  { index: 4, name: "Bala Ged Recovery // Bala Ged Sanctuary" },
  { index: 5, name: "Base Camp" },
  { index: 6, name: "Beyeen Veil // Beyeen Coast" },
  { index: 7, name: "Blackbloom Rogue // Blackbloom Bog" },
  { index: 8, name: "Bloodchief's Thirst" },
  { index: 9, name: "Brushfire Elemental" },
  { index: 10, name: "Canyon Jerboa" },
  { index: 11, name: "Cinderclasm" },
  { index: 12, name: "Cleric of Life's Bond" },
  { index: 13, name: "Concerted Defense" },
  { index: 14, name: "Demon's Disciple" },
  { index: 15, name: "Emeria Captain" },
  { index: 16, name: "Fearless Fledgling" },
  { index: 17, name: "Fireblade Charger" },
  { index: 18, name: "Goma Fada Vanguard" },
  { index: 19, name: "Grotag Night-Runner" },
  { index: 20, name: "Iridescent Hornbeetle" },
  { index: 21, name: "Journey to Oblivion" },
  { index: 22, name: "Jwari Disruption // Jwari Ruins" },
  { index: 23, name: "Kabira Takedown // Kabira Plateau" },
  { index: 24, name: "Kargan Warleader" },
  { index: 25, name: "Kazuul's Fury // Kazuul's Cliffs" },
  { index: 26, name: "Khalni Ambush // Khalni Territory" },
  { index: 27, name: "Kitesail Cleric" },
  { index: 28, name: "Kor Blademaster" },
  { index: 29, name: "Lithoform Blight" },
  { index: 30, name: "Lullmage's Domination" },
  { index: 31, name: "Lullmage's Familiar" },
  { index: 32, name: "Makindi Stampede // Makindi Mesas" },
  { index: 33, name: "Malakir Rebirth // Malakir Mire" },
  { index: 34, name: "Merfolk Falconer" },
  { index: 35, name: "Merfolk Windrobber" },
  { index: 36, name: "Mind Carver" },
  { index: 37, name: "Moss-Pit Skeleton" },
  { index: 38, name: "Murasa Rootgrazer" },
  { index: 39, name: "Murasa Sproutling" },
  { index: 40, name: "Paired Tactician" },
  { index: 41, name: "Pelakka Predation // Pelakka Caverns" },
  { index: 42, name: "Ravager's Mace" },
  { index: 43, name: "Relic Amulet" },
  { index: 44, name: "Relic Axe" },
  { index: 45, name: "Relic Golem" },
  { index: 46, name: "Relic Vial" },
  { index: 47, name: "Rockslide Sorcerer" },
  { index: 48, name: "Roiling Regrowth" },
  { index: 49, name: "Roost of Drakes" },
  { index: 50, name: "Ruin Crab" },
  { index: 51, name: "Scion of the Swarm" },
  { index: 52, name: "Sejiri Shelter // Sejiri Glacier" },
  { index: 53, name: "Shadow Stinger" },
  { index: 54, name: "Shatterskull Minotaur" },
  { index: 55, name: "Silundi Vision // Silundi Isle" },
  { index: 56, name: "Skyclave Cleric // Skyclave Basilica" },
  { index: 57, name: "Skyclave Geopede" },
  { index: 58, name: "Skyclave Pick-Axe" },
  { index: 59, name: "Skyclave Plunder" },
  { index: 60, name: "Skyclave Shadowcat" },
  { index: 61, name: "Soaring Thought-Thief" },
  { index: 62, name: "Song-Mad Treachery // Song-Mad Ruins" },
  { index: 63, name: "Spikefield Hazard // Spikefield Cave" },
  { index: 64, name: "Spoils of Adventure" },
  { index: 65, name: "Springmantle Cleric" },
  { index: 66, name: "Sure-Footed Infiltrator" },
  { index: 67, name: "Tangled Florahedron // Tangled Vale" },
  { index: 68, name: "Taunting Arbormage" },
  { index: 69, name: "Thundering Rebuke" },
  { index: 70, name: "Thundering Sparkmage" },
  { index: 71, name: "Thwart the Grave" },
  { index: 72, name: "Umara Mystic" },
  { index: 73, name: "Umara Wizard // Umara Skyfalls" },
  { index: 74, name: "Vastwood Fortification // Vastwood Thicket" },
  { index: 75, name: "Vastwood Surge" },
  { index: 76, name: "Veteran Adventurer" },
  { index: 77, name: "Vine Gecko" },
  { index: 78, name: "Windrider Wizard" },
  { index: 79, name: "Zof Consumption // Zof Bloodbog" },
];

export const znrData = [
  [
    { index: 32, name: "Makindi Stampede // Makindi Mesas" },
    { index: 18, name: "Goma Fada Vanguard" },
    { index: 47, name: "Rockslide Sorcerer" },
  ],
  [
    { index: 8, name: "Bloodchief's Thirst" },
    { index: 7, name: "Blackbloom Rogue // Blackbloom Bog" },
    { index: 78, name: "Windrider Wizard" },
  ],
  [
    { index: 10, name: "Canyon Jerboa" },
    { index: 79, name: "Zof Consumption // Zof Bloodbog" },
    { index: 58, name: "Skyclave Pick-Axe" },
  ],
  [
    { index: 55, name: "Silundi Vision // Silundi Isle" },
    { index: 78, name: "Windrider Wizard" },
    { index: 57, name: "Skyclave Geopede" },
  ],
  [
    { index: 3, name: "Attended Healer" },
    { index: 11, name: "Cinderclasm" },
    { index: 4, name: "Bala Ged Recovery // Bala Ged Sanctuary" },
  ],
  [
    { index: 23, name: "Kabira Takedown // Kabira Plateau" },
    { index: 69, name: "Thundering Rebuke" },
    { index: 44, name: "Relic Axe" },
  ],
  [
    { index: 27, name: "Kitesail Cleric" },
    { index: 8, name: "Bloodchief's Thirst" },
    { index: 29, name: "Lithoform Blight" },
  ],
  [
    { index: 30, name: "Lullmage's Domination" },
    { index: 49, name: "Roost of Drakes" },
    { index: 1, name: "Akoum Warrior // Akoum Teeth" },
  ],
  [
    { index: 49, name: "Roost of Drakes" },
    { index: 30, name: "Lullmage's Domination" },
    { index: 3, name: "Attended Healer" },
  ],
  [
    { index: 14, name: "Demon's Disciple" },
    { index: 57, name: "Skyclave Geopede" },
    { index: 74, name: "Vastwood Fortification // Vastwood Thicket" },
  ],
  [
    { index: 10, name: "Canyon Jerboa" },
    { index: 6, name: "Beyeen Veil // Beyeen Coast" },
    { index: 72, name: "Umara Mystic" },
  ],
  [
    { index: 9, name: "Brushfire Elemental" },
    { index: 36, name: "Mind Carver" },
    { index: 55, name: "Silundi Vision // Silundi Isle" },
  ],
  [
    { index: 3, name: "Attended Healer" },
    { index: 63, name: "Spikefield Hazard // Spikefield Cave" },
    { index: 64, name: "Spoils of Adventure" },
  ],
  [
    { index: 0, name: "Acquisitions Expert" },
    { index: 4, name: "Bala Ged Recovery // Bala Ged Sanctuary" },
    { index: 12, name: "Cleric of Life's Bond" },
  ],
  [
    { index: 1, name: "Akoum Warrior // Akoum Teeth" },
    { index: 13, name: "Concerted Defense" },
    { index: 57, name: "Skyclave Geopede" },
  ],
  [
    { index: 27, name: "Kitesail Cleric" },
    { index: 28, name: "Kor Blademaster" },
    { index: 37, name: "Moss-Pit Skeleton" },
  ],
  [
    { index: 43, name: "Relic Amulet" },
    { index: 48, name: "Roiling Regrowth" },
    { index: 73, name: "Umara Wizard // Umara Skyfalls" },
  ],
  [
    { index: 28, name: "Kor Blademaster" },
    { index: 6, name: "Beyeen Veil // Beyeen Coast" },
    { index: 51, name: "Scion of the Swarm" },
  ],
  [
    { index: 51, name: "Scion of the Swarm" },
    { index: 63, name: "Spikefield Hazard // Spikefield Cave" },
    { index: 75, name: "Vastwood Surge" },
  ],
  [
    { index: 0, name: "Acquisitions Expert" },
    { index: 25, name: "Kazuul's Fury // Kazuul's Cliffs" },
    { index: 30, name: "Lullmage's Domination" },
  ],
  [
    { index: 26, name: "Khalni Ambush // Khalni Territory" },
    { index: 16, name: "Fearless Fledgling" },
    { index: 59, name: "Skyclave Plunder" },
  ],
  [
    { index: 41, name: "Pelakka Predation // Pelakka Caverns" },
    { index: 18, name: "Goma Fada Vanguard" },
    { index: 36, name: "Mind Carver" },
  ],
  [
    { index: 4, name: "Bala Ged Recovery // Bala Ged Sanctuary" },
    { index: 27, name: "Kitesail Cleric" },
    { index: 76, name: "Veteran Adventurer" },
  ],
  [
    { index: 8, name: "Bloodchief's Thirst" },
    { index: 33, name: "Malakir Rebirth // Malakir Mire" },
    { index: 35, name: "Merfolk Windrobber" },
  ],
  [
    { index: 0, name: "Acquisitions Expert" },
    { index: 17, name: "Fireblade Charger" },
    { index: 37, name: "Moss-Pit Skeleton" },
  ],
  [
    { index: 23, name: "Kabira Takedown // Kabira Plateau" },
    { index: 34, name: "Merfolk Falconer" },
    { index: 5, name: "Base Camp" },
  ],
  [
    { index: 18, name: "Goma Fada Vanguard" },
    { index: 53, name: "Shadow Stinger" },
    { index: 63, name: "Spikefield Hazard // Spikefield Cave" },
  ],
  [
    { index: 12, name: "Cleric of Life's Bond" },
    { index: 13, name: "Concerted Defense" },
    { index: 63, name: "Spikefield Hazard // Spikefield Cave" },
  ],
  [
    { index: 4, name: "Bala Ged Recovery // Bala Ged Sanctuary" },
    { index: 54, name: "Shatterskull Minotaur" },
    { index: 78, name: "Windrider Wizard" },
  ],
  [
    { index: 54, name: "Shatterskull Minotaur" },
    { index: 35, name: "Merfolk Windrobber" },
    { index: 6, name: "Beyeen Veil // Beyeen Coast" },
  ],
  [
    { index: 78, name: "Windrider Wizard" },
    { index: 56, name: "Skyclave Cleric // Skyclave Basilica" },
    { index: 27, name: "Kitesail Cleric" },
  ],
  [
    { index: 9, name: "Brushfire Elemental" },
    { index: 21, name: "Journey to Oblivion" },
    { index: 67, name: "Tangled Florahedron // Tangled Vale" },
  ],
  [
    { index: 6, name: "Beyeen Veil // Beyeen Coast" },
    { index: 72, name: "Umara Mystic" },
    { index: 78, name: "Windrider Wizard" },
  ],
];
